export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const TOGGLE_SHOW_COMPLETED = 'TOGGLE_SHOW_COMPLETED';
export const ADD_TODO = 'ADD_TODO';
export const ADD_TODOS = 'ADD_TODOS';
export const UPDATE_TODO = 'UPDATE_TODO';